FROM apache/airflow:2.9.1

LABEL maintainer="CDT Team"

USER root
RUN apt-get update && apt-get install -y --no-install-recommends \
    libgomp1 \
    libglib2.0-0 \
    libgl1-mesa-glx \
    && rm -rf /var/lib/apt/lists/*
USER airflow

RUN pip install --no-cache-dir \
    "scipy>=1.13" \
    SimpleITK==2.3.1 \
    "scikit-image>=0.23" \
    structlog==24.1.0 \
    boto3==1.34.101 \
    meshio==5.3.5 \
    "torch>=2.0" \
    dynamic_network_architectures
